---
- hosts: all
  sudo: true
  vars_files:
    # This just defines a single clipx_secrets variable (which is a string containg the .env file)
    - clipx-secrets.yml
  roles:
  - { role: postgresql, tags: ['db'] }
  - { role: mina, tags: [ 'mina'] }
  - geerlingguy.ruby
  - agios.nginx-unicorn
  - DavidWittman.redis
  - kunik.elasticsearch
