---
- hosts: all
  sudo: true
  vars:
    - redis_bind: 127.0.0.1
  roles:
  - mina
  - rvm_io.rvm1-ruby
  - agios.unicorn-rvm
  - agios.nginx-unicorn
  - Ansibles.postgresql
  - DavidWittman.redis
  - kunik.elasticsearch