---
- hosts: all
  sudo: true
  vars_files:
    # This just defines a single clipx_secrets variable (which is a string containg the .env file)
    - clipx-secrets.yml
  roles:
  - mina
  - rvm_io.rvm1-ruby
  - agios.unicorn-rvm
  - agios.nginx-unicorn
  - Ansibles.postgresql
  - DavidWittman.redis
  - kunik.elasticsearch