---
- name: Create directory for clipx
  file: path=/var/www/clipx owner=ubuntu group=ubuntu state=directory
- name: Copy codeship public key
  authorized_key: user=ubuntu 
                  key="{{ item }}"
  with_file:
    - ../public_keys/codeship-clipx.pub
    - ../public_keys/nemo.pub
- name: Install postgres-dev packages
  apt: name=postgresql-server-dev-9.3 state=present
- name: Copy over the secrets environment file
  copy: content="{{ clipx_secrets }}" dest="/var/www/clipx/shared/.env" owner="ubuntu" group="ubuntu"